databases:
  - name: Rails-budget-app
    databaseName: Rails-budget-app
    user: Rails-budget-app

services:
  - type: web
    name: Rails-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Rails-budget-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false