default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 1234

development:
  <<: *default
  database: Rails_budget_app_development

test:
  <<: *default
  database: Rails_budget_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
