default: &default
  adapter: postgresql
  encoding: unicode
  user: mydatabase
  password: mydatabase
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mydatabase

test:
  <<: *default
  database: mydatabase

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
